# ~/.config/mpv/mpv.conf
# Sets the initial window size to 1280x720
geometry=1280x720
loop-file=inf
single-instance=yes
volume=40

[audio-window]
profile-cond=string.match(filename, "%.mp3$") ~= nil or string.match(filename, "%.ogg$") ~= nil or string.match(filename, "%.flac$") ~= nil or string.match(filename, "%.mka") ~= nil or string.match(filename, "%.opus") ~= nil
keep-open=no
geometry=300x300