Arch: win64
CompatData: ''
Creation_Date: '2025-05-15 02:37:18.609935'
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-2.4.1
Environment: Gaming
Environment_Variables: {}
External_Programs:
    edcd81c9-ced9-437b-85a1-9a76fe24bdee:
        executable: AnomalyLauncher.exe
        folder: /home/shikarazr/.var/app/com.usebottles.bottles/data/bottles/bottles/Stalker/drive_c/Stalker
        id: edcd81c9-ced9-437b-85a1-9a76fe24bdee
        name: AnomalyLauncher
        path: /home/shikarazr/.var/app/com.usebottles.bottles/data/bottles/bottles/Stalker/drive_c/Stalker/AnomalyLauncher.exe
Installed_Dependencies:
- d3dx9
- msls31
- arial32
- times32
- courie32
- d3dcompiler_43
- d3dcompiler_47
- mono
- gecko
- d3dx11
Language: sys
LatencyFleX: latencyflex-v0.1.1
NVAPI: dxvk-nvapi-v0.9.0
Name: Stalker
Parameters:
    custom_dpi: 93
    decorated: true
    discrete_gpu: true
    dxvk: true
    dxvk_nvapi: false
    fixme_logs: false
    fsr: false
    fsr_quality_mode: none
    fsr_sharpening_strength: 2
    fullscreen_capture: false
    gamemode: false
    gamescope: false
    gamescope_borderless: false
    gamescope_fps: 0
    gamescope_fps_no_focus: 0
    gamescope_fullscreen: true
    gamescope_game_height: 0
    gamescope_game_width: 0
    gamescope_scaling: false
    gamescope_window_height: 0
    gamescope_window_width: 0
    latencyflex: false
    mangohud: false
    mangohud_display_on_game_start: true
    mouse_warp: true
    obsvkc: false
    pulseaudio_latency: false
    renderer: gl
    sandbox: false
    sync: fsync
    take_focus: false
    use_be_runtime: true
    use_eac_runtime: true
    use_runtime: false
    use_steam_runtime: false
    versioning_automatic: false
    versioning_compression: false
    versioning_exclusion_patterns: false
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkbasalt: false
    vkd3d: true
    vmtouch: false
    vmtouch_cache_cwd: false
Path: Stalker
Runner: ge-proton7-43
RunnerPath: ''
Sandbox:
    share_net: false
    share_sound: false
State: 0
Uninstallers: {}
Update_Date: '2025-05-15 04:18:25.146406'
VKD3D: vkd3d-proton-2.14.1
Versioning: false
Versioning_Exclusion_Patterns: []
Windows: win10
WorkingDir: ''
data: {}
run_in_terminal: false
session_arguments: ''
